### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by m0wer** [m0wer/rssfilter#13]
```
2024-03-09 10:25:28,021 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-09 10:25:28,021 INFO sqlalchemy.engine.Engine SELECT article.id AS article_id, article.title AS article_title, article.description AS article_description, article.url AS article_url, article.comments_url AS article_comments_url, article.updated AS
article_updated
FROM article
WHERE article.id = ?
2024-03-09 10:25:28,021 INFO sqlalchemy.engine.Engine [cached since 4.584s ago] (5213,)
2024-03-09 10:25:28,022 INFO sqlalchemy.engine.Engine INSERT INTO article (title, description, url, comments_url, updated) VALUES (?, ?, ?, ?, ?)
2024-03-09 10:25:28,022 INFO sqlalchemy.engine.Engine [cached since 4.743s ago] ('29th Week of 2022', '<article class="md-content__inner md-typeset">  <h2 id="computer-science">Computer Science</h2> <h3 id="gnulinux">GNULinux</h3> <h4 id="neomutt"><a h ...
 (981 characters truncated) ... pan></span><span class="git-revision-date-localized-plugin git-revision-date-localized-plugin-iso_date">2022-07-25</span> </span> </aside> </article>', 'https://m0wer.github.io/memento/newsletter/2022_w29/', None, '2024-03-0
9 10:25:28.022130')
2024-03-09 10:25:28,022 INFO sqlalchemy.engine.Engine COMMIT
2024-03-09 10:25:28,224 INFO sqlalchemy.engine.Engine ROLLBACK
192.168.32.5:54650 - "GET /api/v1/feed/4f3e1d44738d433c9466deda724d0ad1/https%3A//news.ycombinator.com/rss HTTP/1.1" 500
[2024-03-09 10:25:28 +0000] [10] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/main.py", line 40, in add_process_time_header
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi_cache/decorator.py", line 169, in inner
    ret = await ensure_async_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi_cache/decorator.py", line 99, in ensure_async_func
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/routers/feed.py", line 43, in get_feed
    modified_feed = feed_module.get_modified_feed(user_id=user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/modules/feed.py", line 84, in get_modified_feed
    session.commit()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1972, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1257, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1232, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4296, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4431, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4392, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO article (title, description, url, comments_url, updated) VALUES (?, ?, ?, ?, ?)]
[parameters: ('Apple curl security incident 12604', '<a href="https://news.ycombinator.com/item?id=39650498">Comments</a>', 'https://daniel.haxx.se/blog/2024/03/08/the-apple-curl-security-incident-12604/', 'https://news.ycombinator.com/item?id=39650498', '2024-03-09 10:25:23.217892')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-03-09 10:25:28,236 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-09 10:25:28,237 INFO sqlalchemy.engine.Engine SELECT user.id, user.first_request, user.last_request
FROM user
WHERE user.id = ?
2024-03-09 10:25:28,237 INFO sqlalchemy.engine.Engine [generated in 0.00010s] ('4f3e1d44738d433c9466deda724d0ad1',)
2024-03-09 10:25:28,250 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2024-03-09 10:25:28,250 INFO sqlalchemy.engine.Engine SELECT article.id AS article_id, article.title AS article_title, article.description AS article_description, article.url AS article_url, article.comments_url AS article_comments_url, article.updated AS article_updated
FROM article
WHERE article.id = ?
2024-03-09 10:25:28,250 INFO sqlalchemy.engine.Engine [cached since 4.813s ago] (5214,)
2024-03-09 10:25:28,251 INFO sqlalchemy.engine.Engine INSERT INTO article (title, description, url, comments_url, updated) VALUES (?, ?, ?, ?, ?)
2024-03-09 10:25:28,251 INFO sqlalchemy.engine.Engine [cached since 4.972s ago] ('22nd Week of 2022', '<article class="md-content__inner md-typeset">  <h2 id="computer-science">Computer Science</h2> <h3 id="gnulinux">GNULinux</h3> <h4 id="neovim"><a hr ... (951 characters truncated) ... pan></span><span class="git-revision-date-localized-plugin git-revision-date-localized-plugin-iso_date">2022-06-06</span> </span> </aside> </article>', 'https://m0wer.github.io/memento/newsletter/2022_w22/', None, '2024-03-0
9 10:25:28.251330')
2024-03-09 10:25:28,252 INFO sqlalchemy.engine.Engine COMMIT
```

**Comment by m0wer** [comment]
See https://github.com/tiangolo/sqlmodel/issues/307 (might help).
